In [1]:
import numpy as np

### Simple Example

In [2]:
my_list = [1, 2, 3]
my_array = np.array(my_list)

In [3]:
type(my_list)

list

In [4]:
type(my_array)

numpy.ndarray

### Creating Numpy Arrays from Objects

In [5]:
my_list = [1, 2, 3]

In [6]:
np.array(my_list)

array([1, 2, 3])

In [7]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods to create Arrays

#### Arange

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
np.arange(4, 37, 4)

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

#### Zeros and Ones

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [15]:
np.ones((6, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

#### Linspace
Return evenly spaced numbers over a specified interval

In [16]:
np.linspace(0, 15, 4)

array([ 0.,  5., 10., 15.])

In [17]:
np.linspace(0, 1, 15)

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

In [18]:
np.linspace(0, 5, 21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

#### Eye
Creates an identity matrix 

In [19]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Random


#### rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over [0, 1)

In [20]:
np.random.rand(3)

array([0.61036414, 0.9426135 , 0.72449247])

In [21]:
np.random.rand(4, 4)

array([[0.35137766, 0.47477173, 0.11044453, 0.52662725],
       [0.67676664, 0.11900449, 0.72981073, 0.4739862 ],
       [0.05722608, 0.53295076, 0.62499369, 0.77214976],
       [0.44857179, 0.48537897, 0.36265313, 0.78387969]])

#### randn
Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike **rand** which is uniform, values closer to zero are more likely to appear. 

In [22]:
np.random.randn(2)

array([1.30418987, 0.12430315])

In [23]:
np.random.randn(5, 5)

array([[ 0.8037347 , -1.50630867,  0.1390186 ,  1.30824645,  1.54392973],
       [ 0.64961637, -1.90979633, -0.54088147,  0.04770308, -0.10885233],
       [ 0.63073239,  0.47550172, -0.5461027 , -0.09416003,  1.05808433],
       [-0.6421572 ,  0.75255568,  0.00605401,  2.60378725, -1.7502108 ],
       [ 2.05431837,  0.53151612,  0.23772286, -1.16464824, -0.07809925]])

#### randint
Returns random integers from low (inclusive) to high (exclusive).

In [24]:
np.random.randint(0, 57)

3

In [25]:
np.random.randint(0, 57, 7)

array([ 6, 11, 15,  4,  6,  4, 33])

#### Seed
Can be used to set the random state, so that the same "random" results can be reproduced. 

In [26]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [27]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

### Array Atributes and Methods

In [28]:
arr = np.arange(0, 30)

In [29]:
randarr = np.random.randint(0, 50, 10)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [31]:
randarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

#### Reshape

In [32]:
arr.reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [33]:
randarr.reshape(2, 5)

array([[38, 18, 22, 10, 10],
       [23, 35, 39, 23,  2]])

#### max, min, argmax, argmin


In [34]:
randarr.max()

np.int64(39)

In [35]:
randarr.min()

np.int64(2)

In [36]:
randarr.argmax()

np.int64(7)

In [37]:
randarr.argmin()

np.int64(9)

### Shape

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [39]:
arr.shape #Vector

(30,)

In [40]:
arr.reshape(1, 30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [41]:
arr.reshape(1, 30).shape

(1, 30)

In [42]:
arr.reshape(30, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [43]:
arr.reshape(30, 1).shape

(30, 1)

### dtype

In [44]:
arr.dtype

dtype('int64')

In [45]:
arr.dtype = 'int32'
arr.dtype

dtype('int32')

In [46]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')