In [1]:
import numpy as np

# Numpy Indexing and Selection

In [2]:
arr = np.arange(0, 21)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

### Bracket indexing and Selection

In [4]:
arr[3]

np.int64(3)

In [5]:
arr[7:9]

array([7, 8])

#### Broadcasting
NumPy arrays differ from normal Python lists because of their ability to broadcast. With lists, you can only reassign parts of a list with new parts of the same size and shape. That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list. With NumPy arrays, you can broadcast a single value across a larger set of values:

In [6]:
arr[0:5] = 100

In [7]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20])

In [14]:
arr = np.arange(0, 21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [15]:
# Important notes On Slices
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr[:] = 87

slice_of_arr

array([87, 87, 87, 87, 87, 87])

In [19]:
arr 
# Now note the changes also occur in our original array!
# Data is not copied, it's a view of the original array! This avoids memory problems!

array([87, 87, 87, 87, 87, 87,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [20]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([87, 87, 87, 87, 87, 87,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

### Indexing a 2D Array 

In [22]:
arr_2d = np.arange(0, 100).reshape(10, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [23]:
arr_2d[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
arr_2d[1][0]

np.int64(10)

In [26]:
arr_2d[1, 0]

np.int64(10)

In [33]:
arr_2d[:2, :3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [34]:
arr_2d[4:6, 5:8]

array([[45, 46, 47],
       [55, 56, 57]])

In [35]:
arr_2d[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [36]:
arr_2d[2::2, ::2]

array([[20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48],
       [60, 62, 64, 66, 68],
       [80, 82, 84, 86, 88]])

### Conditional Section

In [37]:
arr = np.arange(0, 11)

In [38]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [40]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [41]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [42]:
arr[arr < 6]

array([0, 1, 2, 3, 4, 5])